tests:
  - key: ubuntu-x86
    template: rwx-ci-cd.template.yml
    base:
      image: ubuntu:24.04
      config: rwx/base 1.0.0
      arch: x86_64

  - key: ubuntu-arm
    template: rwx-ci-cd.template.yml
    base:
      image: ubuntu:24.04
      config: rwx/base 1.0.0
      arch: arm64
