tests:
  - key: ubuntu-22-04-x86-64
    template: rwx-ci-cd.template.yml
    base:
      image: ubuntu:22.04
      config: rwx/base 1.0.0
      arch: x86_64

  - key: ubuntu-22-04-arm64
    template: rwx-ci-cd.template.yml
    base:
      image: ubuntu:22.04
      config: rwx/base 1.0.0
      arch: arm64

  - key: ubuntu-24-04-x86-64
    template: rwx-ci-cd.template.yml
    base:
      image: ubuntu:24.04
      config: rwx/base 1.0.0
      arch: x86_64

  - key: ubuntu-24-04-arm64
    template: rwx-ci-cd.template.yml
    base:
      image: ubuntu:24.04
      config: rwx/base 1.0.0
      arch: arm64

  - key: alpine-latest
    template: rwx-ci-cd.template.yml
    base:
      image: alpine:latest
      config: none
