tests:
  - key: ubuntu-22-04-x86-64
    template: rwx-ci-cd.ubuntu-22-04.yml
    base:
      image: ubuntu:22.04
      config: rwx/base 1.0.0
      arch: x86_64

  - key: ubuntu-24-04-x86-64
    template: rwx-ci-cd.ubuntu-24-04.yml
    base:
      image: ubuntu:24.04
      config: rwx/base 1.0.0
      arch: x86_64
